- name: Install Apache packages
  apt: pkg={{ item }} state=installed
  with_items:
    - apache2
    - apache2-mpm-event

- name: Enable Apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - actions
    - expires
    - headers
    - info
    - rewrite
    - ssl
  notify: Reload Apache configuration

- name: Configure Apache
  copy: src=common.conf dest=/etc/apache2/conf-enabled/custom.conf mode=0644
  notify: Reload Apache configuration

- name: Configure default Apache site
  template: src=default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf mode=0644
  notify: Reload Apache configuration

# - name: Configure additional Apache sites
#   template: src={{ item }}.conf.j2 dest=/etc/apache2/sites-enabled/{{ item }}.conf mode=0644
#   with_items:
#   - ...
#   notify: Reload Apache configuration

- name: Copy cPanel holding page
  copy: src=cpanel-reserved-url.html dest=/srv/cpanel-reserved-url.html mode=0644
